###
GET http://localhost:3000/task/6532f4a92a102e71b2fc6f08


###
GET http://localhost:3000/task/task?taskId=6532f8d2c214cbae7efe85af

###
GET http://localhost:3000/task/today/6532f4a92a102e71b2fc6f08?day=tue


###
POST http://localhost:3000/task
Content-Type: application/json

{
    "description": "teste description",
    "currentTime": 6000,
    "start": "1111-11-11T11:11:11.111Z",
    "status": "completed",
    "totalTime": 6000,
    "type": "timer",
    "days": {
    "sun": true,
    "mon": false,
    "tue": true,
    "wed": true,
    "thu": true,
    "fri": true,
    "sat": true
    },
    "userId": "6532f4a92a102e71b2fc6f08"
}


###
DELETE http://localhost:3000/task/65319151a5683ab28c86263e


###
PATCH http://localhost:3000/task/64ff455bd5316480ef2020b5
Content-Type: application/json

{
    "description": "teste description",
    "currentTime": 6000,
    "start": "1111-11-11T11:11:11.111Z",
    "status": "completed",
    "totalTime": 8000,
    "type": "timer",
    "days": {
    "sun": true,
    "mon": true,
    "tue": true,
    "wed": true,
    "thu": true,
    "fri": true,
    "sat": true
    }
}

//---------------------USER

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyZjU0ZTYzOWI2ZWExYjAwNjJlMTgiLCJpYXQiOjE2OTgwODEyNzksImV4cCI6MTY5ODE2NzY3OX0.HMwmA_vWpE_9XCKuCs8XWFepyeKIvn-ag323cQjq-bA

###
GET http://localhost:3000/users/6532f54e639b6ea1b0062e18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyZjU0ZTYzOWI2ZWExYjAwNjJlMTgiLCJpYXQiOjE2OTgwODEyNzksImV4cCI6MTY5ODE2NzY3OX0.HMwmA_vWpE_9XCKuCs8XWFepyeKIvn-ag323cQjq-bA

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "name3Test",
    "password": "2312412"
}


###
DELETE http://localhost:3000/users/6532f5022a102e71b2fc6f0a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyZjU0ZTYzOWI2ZWExYjAwNjJlMTgiLCJpYXQiOjE2OTgwODEyNzksImV4cCI6MTY5ODE2NzY3OX0.HMwmA_vWpE_9XCKuCs8XWFepyeKIvn-ag323cQjq-bA
###
PATCH http://localhost:3000/users/6532f54e639b6ea1b0062e18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyZjU0ZTYzOWI2ZWExYjAwNjJlMTgiLCJpYXQiOjE2OTgwODEyNzksImV4cCI6MTY5ODE2NzY3OX0.HMwmA_vWpE_9XCKuCs8XWFepyeKIvn-ag323cQjq-bA
Content-Type: application/json

{
    "name": "nameTestEdit"
}

//--------------------login
###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "name2Test",
    "password": "2312412"
}